Add bind and unbind tests
automationbroker/bundle-lib pull request #125
Opened 2018-07-08 02:26 UTC by jmrodri

2018-07-08 02:26 UTC, jmrodri commented
Current test coverage now

```
ok      github.com/automationbroker/bundle-lib/bundle   0.042s  coverage: 66.5% of statements
ok      github.com/automationbroker/bundle-lib/clients  (cached)        coverage: 42.9% of statements
?       github.com/automationbroker/bundle-lib/crd      [no test files]
ok      github.com/automationbroker/bundle-lib/registries       (cached)        coverage: 73.6% of statements
ok      github.com/automationbroker/bundle-lib/registries/adapters      (cached)        coverage: 35.8% of statements
ok      github.com/automationbroker/bundle-lib/registries/adapters/oauth        (cached)        coverage: 29.3% of statements
ok      github.com/automationbroker/bundle-lib/runtime  (cached)        coverage: 29.4% of statements
?       github.com/automationbroker/bundle-lib/runtime/mocks    [no test files]
```

2018-07-08 02:27 UTC, jmrodri commented
Previous test coverage
```
ok      github.com/automationbroker/bundle-lib/bundle   (cached)        coverage: 53.0% of statements
ok      github.com/automationbroker/bundle-lib/clients  (cached)        coverage: 42.9% of statements
?       github.com/automationbroker/bundle-lib/crd      [no test files]
ok      github.com/automationbroker/bundle-lib/registries       (cached)        coverage: 73.6% of statements
ok      github.com/automationbroker/bundle-lib/registries/adapters      (cached)        coverage: 35.8% of statements
ok      github.com/automationbroker/bundle-lib/registries/adapters/oauth        (cached)        coverage: 29.3% of statements
ok      github.com/automationbroker/bundle-lib/runtime  (cached)        coverage: 29.4% of statements
?       github.com/automationbroker/bundle-lib/runtime/mocks    [no test files]
```

2018-07-09 15:47 UTC, shawn-hurley requested changes

2018-07-09 15:47 UTC, shawn-hurley commented on bundle/bind_test.go
> +			if tc.extractedCreds != nil {
We should probably verify that the error is set correctly.

2018-07-09 18:15 UTC, shawn-hurley approved these changes

2018-07-10 04:54 UTC, merged