Bug 1609700 - Use config user/pass if no auth_type
automationbroker/bundle-lib pull request #160
Opened 2018-08-03 14:43 UTC by eriknelson

A regression was introduced with the quay adapter that removed these and broke default logins with user+pass and no `auth_type`. This adds them back in.

2018-08-03 16:22 UTC, jmrodri requested changes
Please add a test for this. Probably can change this one to be more correct:
https://github.com/automationbroker/bundle-lib/blob/master/registries/registry_test.go#L1062-L1074

2018-08-03 17:01 UTC, eriknelson commented
The bug that this PR fixes was effectively stripping the User/Pass combo. The updated test ensures this doesn't happen.

2018-08-13 16:00 UTC, djzager approved these changes

2018-08-13 16:24 UTC, jmrodri approved these changes

2018-08-13 16:25 UTC, merged