Bug 1583049 - Add metrics
automationbroker/bundle-lib pull request #161
Opened 2018-08-08 18:26 UTC by eriknelson

* Updates Gopkg.lock
* Fixes tests based on new deps

2018-08-08 18:51 UTC, djzager approved these changes

2018-08-09 17:34 UTC, shawn-hurley requested changes
Small nit

2018-08-09 17:34 UTC, shawn-hurley commented on metrics/metrics.go
> +	if collector != nil {
I think that I would want to know if the collector is nil and I am not collecting metrics. I think the `recover..Panic` should capture that so we may want to remove this?

2018-08-13 19:02 UTC, shawn-hurley approved these changes

2018-08-13 19:53 UTC, merged