Bug 1599522 - Change error statements when discovery fails but images…
automationbroker/bundle-lib pull request #163
Opened 2018-08-13 13:28 UTC by dymurray

… specified in config

2018-08-13 13:39 UTC, djzager approved these changes

2018-08-13 19:04 UTC, eriknelson requested changes

2018-08-13 19:04 UTC, eriknelson commented on registries/adapters/apiv2_adapter.go
> +		return nil, errors.New("failed to fetch catalog response: [%v] and failed to find images in configuration")
This is missing the argument to the format string (figure it's just err?)

2018-08-13 19:19 UTC, jmrodri requested changes
NACK, what @eriknelson pointed out. Also, the PR description is really long. Whoever commits it please rephrase it to something shorter.

2018-08-14 13:18 UTC, dymurray commented
Thanks @eriknelson and @jmrodri. updated.

2018-08-14 17:28 UTC, jmrodri approved these changes

2018-08-14 17:28 UTC, jmrodri commented
@eriknelson issue was addressed by @dymurray so I'm merging this.

2018-08-14 17:28 UTC, merged