Bug 1622964 - Add token refresh to bootstrap loop for apiv2 adapter
automationbroker/bundle-lib pull request #168
Opened 2018-08-28 19:44 UTC by dymurray

2018-08-28 20:36 UTC, jmrodri requested changes

2018-08-28 20:36 UTC, jmrodri commented on registries/adapters/apiv2_adapter.go
> +	err := apiv2a.client.Getv2()
apiv2a fails travis

2018-08-29 12:24 UTC, dymurray commented
Gotta figure out how to fix the test that I wrote for an invalid URL.

2018-08-30 19:02 UTC, dymurray commented on registries/adapters/apiv2_adapter_test.go
> +	serv := adaptertest.GetAPIV2Server(t, false)
This is better because we are using a real APIv2 endpoint that simply doesn't have /v2/_catalog

2018-08-30 19:03 UTC, mhrivnak approved these changes

2018-08-30 20:35 UTC, eriknelson approved these changes

2018-08-30 20:52 UTC, merged