add JFrog registry adapter
automationbroker/bundle-lib pull request #64
Opened 2018-05-01 08:13 UTC by johnkim76

Implement the JFrog registry adapter

2018-05-10 13:09 UTC, dymurray commented
@johnkim76 is this still WIP? Looks like it needs a rebase but it looks ready to go otherwise.

2018-05-10 13:13 UTC, dymurray commented on registries/adapters/jfrog_adapter.go
> +	log.Debug("BundleSpecLabel: %s", BundleSpecLabel)
should be `log.Debugf` wherever there is variable substitution in the string

2018-05-10 13:19 UTC, dymurray requested changes

2018-05-10 13:19 UTC, dymurray commented on registries/adapters/jfrog_adapter.go
> +	log.Debug("Loading image list for URL: [ %v ]", r.Config.URL)
same as above

2018-05-10 13:19 UTC, dymurray commented on registries/adapters/jfrog_adapter.go
> +	}{}
Is this supposed to be here?

2018-05-10 13:19 UTC, dymurray commented on registries/adapters/jfrog_adapter.go
> +	}{}
Is this supposed to be here?

2018-05-10 13:19 UTC, dymurray commented on registries/adapters/jfrog_adapter_test.go
> +
Since we haven't done the v2 schema before with digests I would like to see some tests around `getDigest` and `digestToSpec`

2018-07-10 20:47 UTC, johnkim76 commented
closing this PR since the API V2 adapter will support JFrog, or any API V2 registry adapter.

2018-07-10 20:47 UTC, closed without merging