Allow Bundle to run in a target namespace
automationbroker/bundle-lib pull request #69
Opened 2018-05-02 18:22 UTC by shawn-hurley

fixes #51 

~~depends on #65~~

2018-05-09 22:06 UTC, jmrodri requested changes
I think we should create the context after we get the service account and namespace in all of the places.

2018-05-09 22:06 UTC, jmrodri commented on bundle/bind.go
> +		ns := fmt.Sprintf(fmt.Sprintf("%s-%.4s-", instance.Spec.FQName, bindAction))
Why do we `fmt.Sprintf` twice?

2018-05-09 22:06 UTC, jmrodri commented on bundle/bind.go
> +		ec.Location = namespace
The order of this initialization feels weird. We create the `ExecutionContext` (partially), then get 2 values, which we add to the context. Feels like we should get the `serviceAccount` and the `namespace` first, handle the error. If it's okay, then create the ExecutionContext.

2018-05-09 22:06 UTC, jmrodri commented on bundle/deprovision.go
> +		ns := fmt.Sprintf(fmt.Sprintf("%s-%.4s-", instance.Spec.FQName, deprovisionAction))
Double `fmt.Sprintf`?

2018-05-09 22:06 UTC, jmrodri commented on bundle/deprovision.go
> +		serviceAccount, namespace, err := runtime.Provider.CreateSandbox(pn, ns, targets, clusterConfig.SandboxRole, labels)
Same comment as above.

2018-05-10 13:46 UTC, dymurray commented on bundle/bind.go
> +		ns := fmt.Sprintf(fmt.Sprintf("%s-%.4s-", instance.Spec.FQName, bindAction))
+1 seems redundant

2018-05-10 13:54 UTC, dymurray commented on bundle/bind.go
> +			log.Errorf("Problem executing apb [%s] bind", ec.BundleName)
`Problem executing bundle [%s] bind` for consistency

2018-05-10 13:56 UTC, dymurray commented
The approach makes sense to me. Just a couple nits and questions Jesus mentioned but other than that looks good.

2018-05-18 02:31 UTC, jmrodri commented
@shawn-hurley needs a rebase

2018-05-18 14:04 UTC, jmrodri approved these changes
ACK

2018-05-18 15:40 UTC, dymurray approved these changes

2018-05-18 15:41 UTC, merged