Bug 1576881 - Add discovery to openshift adapter
automationbroker/bundle-lib pull request #77
Opened 2018-05-10 18:08 UTC by dymurray

2018-05-11 13:41 UTC, jmrodri approved these changes
ACK

2018-05-11 14:00 UTC, jwmatthews commented
I have some concerns with the naming of this adapter, I think it's misleading.

The support we added in this PR was for the partner side of the RHCC registry.
It is using a combination of "Openshift Registry" for images and a custom catalog v2 endpoint they implemented themselves, it's not a fair representation of an "OpenShift Registry".

If we are considering the specific image registry implemented provided by "OpenShift Registry" it does __not__ support catalog v2 API.

There is an unrelated effort to implement an ability to list images in the actual OpenShift Registry being tracked in this card and planned for OCP 3.11:  https://trello.com/c/AZINw5qI

I think we should consider a name change of this adapter to be clearer in it's intent, perhaps something like "partner_rhcc".

2018-05-11 14:01 UTC, jwmatthews requested changes
Please re-evaluate the name of this adapter, I think calling it "openshift_adapter" is misleading.

2018-05-14 14:17 UTC, dymurray commented
@jwmatthews  +1 to using `partner_rhcc`. Will make the change. Long term solution I think that we need to combine the different registry adapters which are implementing the docker registry API that is specified [here](https://docs.docker.com/registry/spec/api/) into one adapter that can handle the different schema responses so that our naming is more consistent.

2018-05-14 20:10 UTC, dymurray commented
Waiting on review of these changes before I make them to #74

2018-05-15 14:46 UTC, jwmatthews reviewed
Name change looks good to me.

2018-05-15 14:47 UTC, jwmatthews approved these changes

2018-05-15 15:08 UTC, eriknelson approved these changes
VISACK

2018-05-15 15:08 UTC, eriknelson commented on registries/adapters/partner_rhcc_adapter_test.go
> +func TestPartnerGetImageNames(t *testing.T) {
:+1:

2018-05-15 15:29 UTC, shawn-hurley approved these changes

2018-05-15 15:29 UTC, merged