fixed the mistake of the target image naming
automationbroker/bundle-lib pull request #83
Opened 2018-05-17 08:07 UTC by jianzhangbjz

The correct name of the image should be `registry.reg-aws.openshift.com:443/openshift3/mediawiki-apb:v3.10`, not the `openshift/openshift3/mediawiki-apb:v3.10`. Fixed bug [1579216](https://bugzilla.redhat.com/show_bug.cgi?id=1579216).

2018-05-17 14:27 UTC, shawn-hurley requested changes

2018-05-17 14:27 UTC, shawn-hurley commented on registries/adapters/openshift_adapter_test.go
> -	ft.Equal(t, ocpa.RegistryName(), "openshift", "openshift name does not match `openshift`")
I would prefer we don't delete the test, rather check that the prefix was removed.

2018-05-17 14:28 UTC, shawn-hurley commented
Also if this is fixing a bug for the 3.10 openshift release we need another PR made against the `release-0.1` branch.

2018-05-17 17:43 UTC, dymurray commented
Thanks for the fix @jianzhangbjz. @johnkim76 since I saw you on the bug I will echo @shawn-hurley's comment that we need an associated fix for `release-0.1`

2018-05-18 01:24 UTC, jianzhangbjz commented on registries/adapters/openshift_adapter_test.go
> -	ft.Equal(t, ocpa.RegistryName(), "openshift", "openshift name does not match `openshift`")
Sounds good. I will add it. Thank you!

2018-05-18 05:00 UTC, jianzhangbjz commented
@shawn-hurley Thank you! I added the test case for it. Please have a review. @dymurray Do I need to submit a new PR to the branch `release-0.1`?

2018-05-18 11:39 UTC, dymurray approved these changes

2018-05-18 12:40 UTC, shawn-hurley approved these changes

2018-05-18 12:42 UTC, shawn-hurley commented
@dymurray @jianzhangbjz I can just cherry pick and create a PR for you, or you can open one against the release branch. We don't have a bot that will do it for us like openshift-ansible :(

2018-05-18 14:34 UTC, jianzhangbjz commented
@shawn-hurley Thanks, that's not bad, we can add it later. Here is the new PR #85  for the `release-0.1` branch. Please have a reivew. And, do I need to squash the two commits?

2018-05-18 15:42 UTC, dymurray commented
Thanks @jianzhangbjz ! No need to squash it will do it manually

2018-05-18 15:43 UTC, merged